# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-31 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='equipment_data',
            fields=[
                ('equipment_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('photo', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.CharField(blank=True, max_length=550, null=True)),
                ('use', models.CharField(blank=True, max_length=500, null=True)),
                ('features', models.CharField(blank=True, max_length=250, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('institue', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
