# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-31 16:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment_data',
            old_name='institue',
            new_name='institute',
        ),
    ]
