# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-01 04:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_auto_20170331_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment_data',
            name='institute_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equipment_data',
            name='institute',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
