# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-31 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biotechpark', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='biotech_data',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
