# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-26 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='prof_data',
            fields=[
                ('p_id', models.IntegerField(primary_key=True, serialize=False)),
                ('image', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=13, null=True)),
                ('emailid', models.CharField(max_length=30, null=True)),
                ('specialization', models.CharField(max_length=100, null=True)),
                ('affliation', models.CharField(max_length=100, null=True)),
                ('edu_degree', models.CharField(max_length=100, null=True)),
                ('edu_institute', models.CharField(max_length=100, null=True)),
                ('papers', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
