# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-26 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_datas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prof_data',
            name='p_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
