# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-27 09:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_datas', '0003_auto_20170327_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='student_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='user_datas.student_data'),
        ),
    ]
