# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-27 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_datas', '0004_projects_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='prof_data',
            name='affliation_type',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='prof_data',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
