# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-29 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_datas', '0006_auto_20170328_0758'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_data',
            name='cpi',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
