# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-31 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_datas', '0007_student_data_cpi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='student_id',
        ),
        migrations.RenameField(
            model_name='student_data',
            old_name='place',
            new_name='city',
        ),
        migrations.RemoveField(
            model_name='prof_data',
            name='affliation',
        ),
        migrations.RemoveField(
            model_name='prof_data',
            name='affliation_type',
        ),
        migrations.RemoveField(
            model_name='prof_data',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='prof_data',
            name='edu_degree',
        ),
        migrations.RemoveField(
            model_name='prof_data',
            name='edu_institute',
        ),
        migrations.RemoveField(
            model_name='prof_data',
            name='papers',
        ),
        migrations.RemoveField(
            model_name='prof_data',
            name='specialization',
        ),
        migrations.RemoveField(
            model_name='student_data',
            name='cpi',
        ),
        migrations.RemoveField(
            model_name='student_data',
            name='current_year',
        ),
        migrations.AddField(
            model_name='student_data',
            name='type1',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.DeleteModel(
            name='projects',
        ),
    ]
