# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-31 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_datas', '0008_auto_20170331_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prof_data',
            name='emailid',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='prof_data',
            name='image',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prof_data',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='prof_data',
            name='phone',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='student_data',
            name='emailid',
            field=models.CharField(max_length=90, null=True),
        ),
    ]
