# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-01 04:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_datas', '0010_auto_20170331_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_data',
            name='specialization',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
