# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-28 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='survey_data',
            fields=[
                ('survey_id', models.AutoField(primary_key=True, serialize=False)),
                ('access_token', models.CharField(blank=True, max_length=250, null=True)),
                ('user_type', models.IntegerField(default=1)),
                ('title', models.CharField(blank=True, max_length=80, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('question1', models.CharField(blank=True, max_length=120, null=True)),
                ('question2', models.CharField(blank=True, max_length=120, null=True)),
                ('question3', models.CharField(blank=True, max_length=120, null=True)),
                ('question4', models.CharField(blank=True, max_length=120, null=True)),
                ('modified', models.DateField(auto_now=True, null=True)),
                ('created', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
