# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-28 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey_data',
            name='permission',
            field=models.FileField(blank=True, null=True, upload_to='resources'),
        ),
    ]
