# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-31 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_survey_data_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey_data',
            name='city',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
