# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-31 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_survey_data_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey_data',
            name='filled',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
