# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-31 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='research_data',
            fields=[
                ('survey_id', models.AutoField(primary_key=True, serialize=False)),
                ('access_token', models.CharField(blank=True, max_length=250, null=True)),
                ('title', models.CharField(blank=True, max_length=80, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('city', models.CharField(blank=True, max_length=500, null=True)),
                ('field', models.CharField(blank=True, max_length=100, null=True)),
                ('modified', models.DateField(auto_now=True, null=True)),
                ('created', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
