# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-31 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incubators', '0002_auto_20170328_0758'),
    ]

    operations = [
        migrations.AddField(
            model_name='incubators_data',
            name='facilities',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
