# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-31 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incubators', '0004_auto_20170331_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='incubators_data',
            name='latitude',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='incubators_data',
            name='longitude',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='incubators_data',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
