# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-01 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incubators', '0005_auto_20170331_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='incubators_data',
            name='image',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
