# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-01 04:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0002_auto_20170401_0958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institute_data',
            old_name='emailid',
            new_name='website',
        ),
        migrations.RemoveField(
            model_name='institute_data',
            name='contact_designation',
        ),
        migrations.RemoveField(
            model_name='institute_data',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='institute_data',
            name='contact_name',
        ),
        migrations.RemoveField(
            model_name='institute_data',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='institute_data',
            name='specialization',
        ),
        migrations.AlterField(
            model_name='institute_data',
            name='image',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
