# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-01 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0003_auto_20170401_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute_data',
            name='image',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='institute_data',
            name='website',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
